### PR TITLE
merge lawson/workflows into main

### PR DESCRIPTION
**Pull request by lalewis1**
added support for upload action on push to main.

### CODE REVIEW

**Review by jamiefeiss — APPROVED** [review]
Looks good. I've also added the repo secrets required for this workflow.

**Comment by lalewis1** [comment]
I assume then that once I merge this it will try to upload the background and vocabs 😬🫣

**Comment by lalewis1** [comment]
I noticed the upload action here has not uploaded anything because i added the new vocab file in the previous commit. @jamiefeiss do you know of an easy way to get that to upload? or should i just merge a new commit with a dummy change to the vocabs directory so that the action will run and upload them all.

**Comment by jamiefeiss** [comment]
@lalewis1 You should be able to run the workflow manually on GitHub - Actions > Workflow page > Run Workflow

**Comment by lalewis1** [comment]
I could but I think it would skip the upload because it thinks no files have been changed

**Pull request merged**
